export const config = Object.freeze({
    search: {
        apiUrl: 'http://192.168.188.72:3010',
        tags: [
            'Einkaufshilfe',
            'Kinderbetreuung',
            'Allgemeine Tätigkeiten',
            'Persönliche Betreuung',
            'Haustierbetreuung',
        ],
        locations: [
            'Regensburg',
            'R-Innenstadt',
            'R-Stadtamhof',
            'R-Steinweg - Pfaffenstein',
            'R-Sallern - Gallingkofen',
            'R-Konradsiedlung - Wutzlhofen',
            'R-Brandlberg - Keilberg',
            'R-Reinhausen',
            'R-Weichs',
            'R-Schwabelweis',
            'R-Ostenviertel',
            'R-Kasernenviertel',
            'R-Galgenberg',
            'R-Kumpfmühl - Ziegetsdorf - Neuprüll',
            'R-Großprüfening - Dechbetten - Königswiesen',
            'R-Westenviertel',
            'R-Ober- und Niederwinzer - Kager',
            'R-Oberisling - Graß',
            'R-Burgweinting - Harting',
            'Alteglofsheim',
            'Altenthann',
            'Aufhausen',
            'Bach a. d. Donau',
            'Barbing',
            'Beratzhausen',
            'Bernhardswald',
            'Brennberg',
            'Brunn',
            'Deuerling',
            'Donaustauf',
            'Duggendorf',
            'Hagelstadt',
            'Hemau',
            'Holzheim a. Forst',
            'Kallmünz',
            'Köfering',
            'Laaber',
            'Lappersdorf',
            'Mintraching',
            'Mötzing',
            'Neutraubling',
            'Nittendorf',
            'Obertraubling',
            'Pentling',
            'Pettendorf',
            'Pfakofen',
            'Pfatter',
            'Pielenhofen',
            'Regenstauf',
            'Riekofen',
            'Schierling',
            'Sinzing',
            'Sünching',
            'Tegernheim',
            'Thalmassing',
            'Wenzenbach',
            'Wiesent',
            'Wörth a. d. Donau',
            'Wolfsegg',
            'Zeitlarn',
        ]
    }
});