export const config = Object.freeze({
    search: {
        tags: [
            'Einkaufshilfe',
            'Kinderbetreuung',
            'Allgemeine Tätigkeiten',
            'Persönliche Betreuung',
            'Haustierbetreuung',
        ],
        locations: [
            'Regensburg',
            'Alteglofsheim',
            'Altenthann',
            'Aufhausen',
            'Bach a. d. Donau',
            'Barbing',
            'Beratzhausen',
            'Bernhardswald',
            'Brennberg',
            'Brunn',
            'Deuerling',
            'Donaustauf',
            'Duggendorf',
            'Hagelstadt',
            'Hemau',
            'Holzheim a. Forst',
            'Kallmünz',
            'Köfering',
            'Laaber',
            'Lappersdorf',
            'Mintraching',
            'Mötzing',
            'Neutraubling',
            'Nittendorf',
            'Obertraubling',
            'Pentling',
            'Pettendorf',
            'Pfakofen',
            'Pfatter',
            'Pielenhofen',
            'Regenstauf',
            'Riekofen',
            'Schierling',
            'Sinzing',
            'Sünching',
            'Tegernheim',
            'Thalmassing',
            'Wenzenbach',
            'Wiesent',
            'Wörth a. d. Donau',
            'Wolfsegg',
            'Zeitlarn',
        ]
    }
});