export const config = Object.freeze({
    search: {
        apiUrl: 'http://192.168.188.72:3010',
        tags: [
            'Einkaufshilfe',
            'Kinderbetreuung',
            'Allgemeine Tätigkeiten',
            'Persönliche Betreuung',
            'Haustierbetreuung',
        ],
        locationsMapping: {
            'R': 'Regensburg',
            'W': 'Würzburg',
            'NM': 'Neumarkt (i.d. OPf.)',
            'SR': 'Straubing-Bogen'
        },
        municipals: [
            'R',
            'W'
        ],
        locations: {
            'R': [
                'Regensburg',
                'R-Innenstadt',
                'R-Stadtamhof',
                'R-Steinweg - Pfaffenstein',
                'R-Sallern - Gallingkofen',
                'R-Konradsiedlung - Wutzlhofen',
                'R-Brandlberg - Keilberg',
                'R-Reinhausen',
                'R-Weichs',
                'R-Schwabelweis',
                'R-Ostenviertel',
                'R-Kasernenviertel',
                'R-Galgenberg',
                'R-Kumpfmühl - Ziegetsdorf - Neuprüll',
                'R-Großprüfening - Dechbetten - Königswiesen',
                'R-Westenviertel',
                'R-Ober- und Niederwinzer - Kager',
                'R-Oberisling - Graß',
                'R-Burgweinting - Harting',
                'Alteglofsheim',
                'Altenthann',
                'Aufhausen',
                'Bach a. d. Donau',
                'Barbing',
                'Beratzhausen',
                'Bernhardswald',
                'Brennberg',
                'Brunn',
                'Deuerling',
                'Donaustauf',
                'Duggendorf',
                'Hagelstadt',
                'Hemau',
                'Holzheim a. Forst',
                'Kallmünz',
                'Köfering',
                'Laaber',
                'Lappersdorf',
                'Mintraching',
                'Mötzing',
                'Neutraubling',
                'Nittendorf',
                'Obertraubling',
                'Pentling',
                'Pettendorf',
                'Pfakofen',
                'Pfatter',
                'Pielenhofen',
                'Regenstauf',
                'Riekofen',
                'Schierling',
                'Sinzing',
                'Sünching',
                'Tegernheim',
                'Thalmassing',
                'Wenzenbach',
                'Wiesent',
                'Wörth a. d. Donau',
                'Wolfsegg',
                'Zeitlarn',
            ],
            'W': [
                'Würzburg',
                'W-Altstadt',
                'W-Zellerau',
                'W-Dürrbachtal',
                'W-Grombühl',
                'W-Lindleinsmühle',
                'W-Frauenland',
                'W-Sanderau',
                'W-Heidingsfeld',
                'W-Heuchelhof',
                'W-Steinbachtal',
                'W-Versbach',
                'W-Lengfeld',
                'W-Rottenbauer',
                'Altertheim',
                'Aub',
                'Bergtheim',
                'Bieberehren',
                'Bütthard',
                'Eibelstadt',
                'Eisenheim',
                'Eisingen',
                'Erlabrunn',
                'Estenfeld',
                'Frickenhausen am Main',
                'Gaukönigshofen',
                'Gelchsheim',
                'Gerbrunn',
                'Geroldshausen',
                'Giebelstadt',
                'Greußenheim',
                'Güntersleben',
                'Hausen bei Würzburg',
                'Helmstadt',
                'Hettstadt',
                'Höchberg',
                'Holzkirchen',
                'Kirchheim',
                'Kist',
                'Kleinrinderfeld',
                'Kürnach',
                'Leinach',
                'Margetshöchheim',
                'Neubrunn',
                'Oberpleichfeld',
                'Ochsenfurt',
                'Prosselsheim',
                'Randersacker',
                'Reichenberg',
                'Markt Remlingen',
                'Riedenheim',
                'Rimpar',
                'Rottendorf',
                'Röttingen',
                'Sommerhausen',
                'Sonderhofen',
                'Tauberrettersheim',
                'Theilheim',
                'Thüngersheim',
                'Uettingen',
                'Unterpleichfeld',
                'Veitshöchheim',
                'Waldbrunn',
                'Waldbüttelbrunn',
                'Wüstenzell',
                'Winterhausen',
                'Zell am Main'
            ],
            'NM': [
                'Neumarkt (i.d. OPf.)',
                'Berching',
                'Berg',
                'Berngau',
                'Breitenbrunn',
                'Deining',
                'Dietfurt',
                'Freystadt',
                'Hohenfels',
                'Lauterhofen',
                'Lupburg',
                'Mühlhausen',
                'Parsberg',
                'Pilsach',
                'Postbauer-Heng',
                'Pyrbaum',
                'Sengenthal',
                'Seubersdorf',
                'Velburg'
            ],
            'SR': [
                'Straubing',
                'Bogen',
                'Geiselhöring',
                'Mallersdorf-Pfaffenberg',
                'Mitterfels',
                'Schwarzach',
                'Aiterhofen',
                'Hunderdorf',
                'Mitterfels',
                'Rain',
                'Schwarzach',
                'Stallwang',
                'Straßkirchen'
            ]
        },
    }
});